# Generated by Django 3.2.9 on 2022-08-05 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments_and_chats', '0002_auto_20220715_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatchat',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='auth.user'),
            preserve_default=False,
        ),
    ]
