# Generated by Django 3.2.9 on 2022-11-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_verificationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdata',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to='accounts.profiledata'),
        ),
    ]
