# Generated by Django 3.2.9 on 2022-11-22 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_alter_verificationdata_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvatarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, max_length=254, upload_to='img')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
