# Generated by Django 3.2.9 on 2022-11-22 18:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediarating',
            unique_together={('media', 'author')},
        ),
    ]
